config/routes.rb
Rails.application.routes.draw do
  get 'post/show'

  get 'post/new'
  get 'post/edit'
  post 'update' => "post#update"

  root 'post#show'
  post '/delete_post' => "post#delete_post"
  post '/create_post' => "post#create_post"
  get '/api_data' => "post#api_data_for_frontend"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def show
    @posts = Post.paginate(page: params[:page], per_page: 10)
    @allowed_to_delete = true 
  end

  def new
  end

  def delete_post
    @post = Post.find_by_id(params[:id])
    if @post.present?
      @post.destroy
    end
    redirect_to root_path
  end

  def create_post
    user_id = rand(1..10)
    post = Post.new(title: params[:title], body: params[:body],user_id: user_id)
    if post.save
      redirect_to root_path
    else
      redirect_to post_new_path
    end
  end

  def edit
    @post = Post.find_by_id(params[:id])
  end

  def update
    @post = Post.find_by_id(params[:id])
    post_params = {title: params[:title], body: params[:body]}
    @post.update(post_params)
    redirect_to root_path
  end

  def api_data_for_frontend
    @posts = Post.select(:id, :title, :created_at)
    render json: {posts: @posts}
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/post/edit.html.erb
<div class="container">
    <div class="row">
        <div class="jumbotron">
            <h1>Edit Blog</h1>
        </div>
        <form>
            <div class="row">
                <div class="form-group">
                    <input id="title" type="text" class="form-control" value="<%=@post.title%>">
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <input id="body" type="text" class="form-control" value="<%=@post.body%>">
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <button type="button" class="btn btn-primary" onclick="updatePost(<%=@post.id%>)">Update Blog</button>
                </div>
            </div>
            <%=link_to "Back", root_path, class:"btn btn-default"%>
        </form>
</div>
<script>
function updatePost(id){
    var title = $("#title").val()
    var body = $("#body").val()
    $.ajax({
        url: '/update',
        method: "post",
        data: {id: id, title: title, body: body},
    })
}
</script>

app/views/post/new.html.erb
<div class="container">
    <div class="row">
        <div class="jumbotron">
            <h1>Create New Blog</h1>
        </div>
        <form>
            <div class="row">
                <div class="form-group">
                    <input id="title" type="text" class="form-control" placeholder="Enter the Title">
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <input id="body" type="text" class="form-control" placeholder="Enter the Body">
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <button type="button" class="btn btn-primary" onclick="createPost()">Submit</button>
                </div>
            </div>
            <%=link_to "Back", root_path, class:"btn btn-default"%>
        </form>
</div>
<script>
function createPost(){
    var title = $("#title").val()
    var body = $("#body").val()
    $.ajax({
        url: '/create_post',
        method: "post",
        data: {title: title, body: body},
    })
}
</script>

app/views/post/show.html.erb
<div class="container">
    <div class="row">
        <div class="jumbotron">
            <h1>Blogs</h1>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <td>Title</td>
                    <td>Body</td>
                    <td>User Type</td>
                    <td>Action</td>
                    <td>Edit</td>
                </tr>
            </thead>
            <tbody>
                <%@posts.each do |post|%>
                    <tr>
                        <td><%=post.title%></td>
                        <td><%=post.body%></td>
                        <td><%=post.user.user_type.capitalize%></td>
                        <%if @allowed_to_delete%>
                            <td><button type="button" class="btn btn-danger" onclick="deletePost(<%=post.id%>)">Delete</button></td>
                        <%end%>
                        <%if @allowed_to_delete%>
                            <td><%=link_to "Edit", post_edit_path(id: post.id), class:"btn btn-warning"%></td>
                        <%end%>
                    </tr>
                <%end%>
            </tbody>
        </table>
        <div class="container">
            <%= will_paginate @posts %>
        </div>
    </div>
    <div class="container">
        <%=link_to "Create Post", post_new_path, class:"btn btn-primary"%>
    </div>
</div>

<script>
function deletePost(id) {
    $.ajax({
        url: '/delete_post',
        method: "post",
        data: {id: id},
    })
}
</script>